In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv(r'C:\Users\Edunet Foundation\Desktop\Students_handover\Normalisation\wine_data (1).csv')

In [6]:
df.head

<bound method NDFrame.head of      1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29   5.64  1.04  \
0    1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05
1    1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03
2    1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86
3    1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04
4    1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97   6.75  1.05
..  ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...
172  3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64
173  3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70
174  3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59
175  3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60
176  3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61

     3.92  1065
0    3.40  1050
1    3.17  1185
2    3.45  1480
3    2.93   735
4    2.85  1450
..    ...   ...
172  1.74   740
173  1.56   750
174  1.56   835
175  1.62   840
176  1.60   560

[177 rows x 14 columns]>

In [8]:
df = pd.read_csv(r'C:\Users\Edunet Foundation\Desktop\Students_handover\Normalisation\wine_data (1).csv',header=None,usecols=[0,1,2])

In [9]:
df

     0      1     2
0    1  14.23  1.71
1    1  13.20  1.78
2    1  13.16  2.36
3    1  14.37  1.95
4    1  13.24  2.59
..  ..    ...   ...
173  3  13.71  5.65
174  3  13.40  3.91
175  3  13.27  4.28
176  3  13.17  2.59
177  3  14.13  4.10

[178 rows x 3 columns]

In [10]:
df.columns = ['Class label' , 'Alcohol','Malic acid']

In [11]:
df

     Class label  Alcohol  Malic acid
0              1    14.23        1.71
1              1    13.20        1.78
2              1    13.16        2.36
3              1    14.37        1.95
4              1    13.24        2.59
..           ...      ...         ...
173            3    13.71        5.65
174            3    13.40        3.91
175            3    13.27        4.28
176            3    13.17        2.59
177            3    14.13        4.10

[178 rows x 3 columns]